monolog:
    channels:
        - base_api
    handlers:
        base_api:
            type: rotating_file
            filename_format: '{date}_{filename}'
            path: "%kernel.logs_dir%/base_api/base_api_%kernel.environment%.log"
            channels: [ base_api ]
            level: debug
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
